name: Jan Haak
author: Jan Haak
baseurl: ""
description: > 
 tech, software, travel
 
github: https://www.github.com/janhaak
twitter: https://www.twitter.com/janhaak
facebook: https://www.facebook.com/jan.haak
linkedin: https://au.linkedin.com/pub/jan-haak/5/938/582
email: jan@janhaak.com
location: -31.955849, 115.859088
#disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
